name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://bdct02.baidupcs.com/file/05288dc02j981cb9f7516081180afadc?bkt=en-06f5c65000af0ed67b689ca52965c7d75f8eed441cacaf3bfdbc43ddb6ecff18491bdeabe475f065&fid=2914204150-250528-965103531938654&time=1640092807&sign=FDTAXUybGERQlBHSKfWaqi-DCb740ccc5511e5e8fedcff06b081203-Asql7eKHm0wxXAWWnltrShlapR8%3D&to=19,140&size=2767249245&sta_dx=2767249245&sta_cs=0&sta_ft=zip&sta_ct=0&sta_mt=0&fm2=MH%2CBaoding%2CAnywhere%2C%2Cguangdong%2Cct&ctime=1640092215&mtime=1640092806&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=2767249245&vuk=2914204150&iv=2&htype=&randtype=&origin=dlna&tkbind_id=0&esl=1&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-dea7d7fbf9775677ad805f43a2df01d52087b3532f67a4edea7facc6ec6a5f365becd4dfdd28b75f&expires=8h&rt=pr&r=915178264&mlogid=8230877253748438798&vbdid=-&fin=miui_CEPHEUS_21.11.17_aa33d15604_11.0.zip&err_ver=1.0&check_blue=1&rtype=1&devuid=BDIMXV2-O_A7F91578F74F4BC1BC87EBF3D46146BA-C_0-D_0-M_525400923B87-V_0E564ACA&clienttype=25&channel=00000000000000000000000000000000&dp-logid=8230877253748438798&dp-callid=0.1.1&hps=1&tsl=0&csl=0&fsl=-1&csign=zgQPPJ22vQGZbFP0bcM%2FVgi3MUw%3D&so=0&ut=1&uter=-1&serv=0&uc=1026021028&ti=16c8192e22ea32f553349eec85050cd6f4b9fae70d00dfea&sta_eck=1&hflag=30&from_type=3&adg=c_171cbe12b42b6a67af66ec142877bf1b&reqlabel=250528_d_e70e7a462543800756f12fd9540da36a_-1_7fdeec4d37d9c7bd183caa726be65e30&by=themis
  ROM_NAME: Generic
  BUILD_TYPE: Aonly
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
